### ISSUE TITLE
[Mobile App]: Improve Testing Documentation (currently Google Doc)

### ISSUE THREAD

**Issue by novas1r1** [socialincome-san/public#809]

**Comment by KarinBerg** [comment]
Improved the content of the App Testing Guide. https://docs.google.com/document/d/1-y__kbnLX3KCHp2pdXhzq58rbMmnXwUI-Cirihy224o/edit?pli=1

**Comment by ssandino** [comment]
Looking good! Is anything speaking against adding the content to a TESTING.md file on our Repo, so it‘s accessible to anyone?

**Comment by KarinBerg** [comment]
Not sure about the test accounts. Maybe they should not seen by any Github user?!?

**Comment by ssandino** [comment]
So, with these credentials, people would be able to login as recipients if they download the staging app (but they would still need an invitation, right?). It doesn't give them a login to the admin tool. 

I don't see a big risk, but what do you think, @novas1r1 and @MDikkii?

Alternatively, we could hide the login numbers in GitHub and keep them in a separate file. But then again, it would be another file. :.-)

**Comment by KarinBerg** [comment]
@ssandino I don't feel good with making these test accounts public. I would prefer to keep them internally. Maybe in another private repo?

**Comment by ssandino** [comment]
Or we could just put the test account details in a Google Doc, which is protected but can be shared upon request. I think this is easier than using a separate private repo, which can be complicated due to GitHub’s rights management. In the README, we can mention that the details are available upon request instead of including the account details directly. What you think?

**Comment by KarinBerg** [comment]
Done with https://github.com/socialincome-san/public/pull/912
