### ISSUE TITLE
Deployment Process

### ISSUE THREAD

**Issue by andrashee** [socialincome-san/public#91]
The deployment GitHub workflows I configured for the backend and admin, currently deploy code continuously after each merge of a PR into main.

I personally quite like this approach since it's simple, ensures that code is deployed quickly and doesn't add manual overhead.

However, there are other good alternatives. E.g. manually creating a release with semantic versioning in GitHub which then triggers an automatic deployment. This gives you more control of the releasing procedure, but involves more manual steps.

I see pros/cons for both approaches and don't have strong opinions.

Any thoughts
@ssandino, @mkue, @renestalder, @sdwivedi?

**Comment by renestalder** [comment]
We have the one with the release creation currently in the closed-source website project. Reasoning for it was mostly because we weren't able to fully local test changes as we didn't have all Firebase emulators in use and therefore needed more control about when to release.

But if we can say that all changes to main get run against tests, I also believe the current approach of automatic deployment on main is the best.

The native apps and also later the UI (when used in multiple projects) are probably the only packages that would benefit from better release mechanism like automatic changelog generation, automatic version bump and publishing to the release page. But I don't feel line that is something we need now. And this can also be done on merge into main.

**Comment by mkue** [comment]
Agreed. I would keep it as it is for the moment. We can switch to a release based deployment as soon as we think we need it.
